version: '2'
services:
  ucd-server:
    image: ibmcom/ucds
    ports:
      - 8443:8443
      - 7918:7918

  ucd-agent1:
    container_name: ucd-agent1
    image: ibmcom/ucda
    depends_on:
      - ucd-server
      - ucd-relay

  ucd-agent2:
    container_name: ucd-agent2
    image: ibmcom/ucda
    depends_on:
      - ucd-server
      - ucd-relay

  ucd-agent3:
    container_name: ucd-agent3
    image: ibmcom/ucda
    depends_on:
      - ucd-server
      - ucd-relay

  ucd-relay:
    image: ibmcom/ucdr
    ports:
      - 7916:7916
      - 20080:20080
      - 20081:20081
    depends_on:
      - ucd-server
